### ISSUE TITLE
Failed Ajax request or invalid JSON returned.

### ISSUE THREAD

**Issue by aguen** [pkp/customHeader#6]
On OJS 3.1 I receive a 

> Failed Ajax request or invalid JSON returned.

error when clicking "Settings" after installation.

**Comment by asmecher** [comment]
@aguen, how did you install the plugin? Do you see anything relevant in your PHP error log?

**Comment by asmecher** [comment]
This was probably caused by using plugin code that wasn't compatible with the release of OJS/OMP it was installed into. If you're using a released version of OJS, it's best to install this plugin from the Plugin Gallery. If that's not possible, get the appropriate version from the Releases area of the github repository.
